services:

  munishlearn_mysql: 
    image: mysql:8.0
    volumes:
      - munish_learn_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: munish
      MYSQL_DATABASE: munishlearn

  app:
    image: node:16-alpine
    command: sh -c "npm install && node index.js"
    ports:
      - 5000:80
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: munishlearn_mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: munish
      MYSQL_DB: munishlearn

volumes:
  munish_learn_mysql: